[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  # { id = "end-of-file-fixer" },
  { id = "check-yaml" },
  { id = "check-json", exclude = { glob = "examples/**/*.json" } },
  # { id = "pretty-format-json" },
  { id = "mixed-line-ending", fix = "lf" },
]

[[repos]]
repo = "https://github.com/editorconfig-checker/editorconfig-checker.python"
rev = "3.11.1"
hooks = [{ id = "editorconfig-checker" }]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "v2.4.3"
hooks = [
  { id = "codespell" },
]
